<a href="https://colab.research.google.com/github/HinataTsuji/data-science-toolkit/blob/main/Numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# NUMPY Library

import numpy as np

In [ ]:
#numpy is like an array of number (2d and 3d array)
a=np.array([1,2,3])
print(type(a), a.shape, a[1])
a[0]=10 #reading or writing
print(a)

<class 'numpy.ndarray'> (3,) 2
[10  2  3]


In [ ]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(b.shape)

threedarray=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(threedarray)
print(threedarray.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [ ]:
print(b[0,0],b[1,1])

1 5


In [ ]:
n1=np.zeros((2,2))   #two rows, two columns with zeros all of it
print(n1)

[[0. 0.]
 [0. 0.]]


In [ ]:
n2=np.ones((1,2))
print(n2)   #the dots of zeros and ones indicate that they are float TYPE by default

[[1. 1.]]


In [ ]:
n3=np.full((2,2),7)   #fill everything with 7
print(n3)

[[7 7]
 [7 7]]


In [ ]:
n4=np.eye(3) #identity matrics
print(n4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
num4=np.random.random((2,2))  #generate any floating number in 2 rows and 2 columns (default range of values are from 0 to 1), can discover ourselves
print(num4)

[[0.54748071 0.8029421 ]
 [0.7341057  0.46968146]]


In [ ]:
any_var=b[1,:2]  #reading height -> width -> length
print(any_var)

[4 5]
