<a href="https://colab.research.google.com/github/HinataTsuji/data-science-toolkit/blob/main/Tutorial03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np  #library to deal with multidimensional arrays
import random

#Create a numpy array of size 2 x 2 (2 rows and 2 columns)
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [4]:
#Create a random numpy array of size 3 x 4
b = np.random.randint(1, 101, size=(3,4))
b2 = np.random.rand(3,4) #range of random is from 0 to 1
print(b)
print(f'\n{b2}')

[[79 73 32 20]
 [70 49 18  5]
 [87 70 82 39]]

[[0.54387699 0.97349006 0.22892569 0.38884481]
 [0.65855401 0.2262652  0.36932071 0.53364915]
 [0.35134284 0.74563772 0.48202372 0.96927024]]


In [ ]:
#Create a numpy array of ones
c = np.ones((3,3))
#Create a numpy array of zeroes
d = np.zeros((3,3))
print(c)
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# Create a random numpy array of size 6x3 and transpose it
e = np.random.rand(6,3)
print(e)

f = np.transpose(e) #invert an array rows become columns, columns become rows
f2 = e.T  #transpose
print(f)
print('\n',f2)

[[0.36063507 0.78781307 0.92054746]
 [0.70904812 0.57461336 0.29499816]
 [0.02282547 0.59726975 0.81830968]
 [0.09511169 0.84638486 0.46824665]
 [0.2063208  0.15733672 0.21523042]
 [0.71739663 0.29511069 0.47430785]]
[[0.36063507 0.70904812 0.02282547 0.09511169 0.2063208  0.71739663]
 [0.78781307 0.57461336 0.59726975 0.84638486 0.15733672 0.29511069]
 [0.92054746 0.29499816 0.81830968 0.46824665 0.21523042 0.47430785]]

 [[0.36063507 0.70904812 0.02282547 0.09511169 0.2063208  0.71739663]
 [0.78781307 0.57461336 0.59726975 0.84638486 0.15733672 0.29511069]
 [0.92054746 0.29499816 0.81830968 0.46824665 0.21523042 0.47430785]]


In [9]:
# Create two random numpy array of size n x p and p x m
# and then compute the dot product

# Define the dimensions
# In this example, it is A = 2 x 3 matrix, B = 3 x 4 matrix
n = 2 # Number of rows for the first array
p = 3 # Number of columns for the first array and rows for the second array
m = 4 # Number of columns for the second array

# Create the random arrays and calculate the dot product
g = np.random.random((n,p))
h = np.random.random((p,m))
dotprod = np.dot(g, h)
print(g)
print(h)
print(dotprod)

[[0.81809889 0.46060789 0.66381395]
 [0.05942464 0.5027363  0.81489978]]
[[0.37447285 0.60332391 0.13214506 0.10730575]
 [0.7546097  0.08392496 0.38910341 0.39867829]
 [0.63429713 0.69684561 0.05578189 0.87977681]]
[[1.07499029 0.99481095 0.32436063 0.8554292 ]
 [0.91851119 0.64590377 0.24892573 0.92373659]]
