<a href="https://colab.research.google.com/github/HinataTsuji/data-science-toolkit/blob/library%2Fnumpy/Tutorial03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [4]:
b = np.random.randint(1, 101, size=(3,4))
print(b)

[[62  5 96 64]
 [27 79 64 71]
 [83 38 10 97]]


In [7]:
c = np.ones((3,3))
d = np.zeros((3,3))
print(c)
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
e = np.random.random((6,3))
print(e)

f = np.transpose(e) #invert an array rows become columns, columns become rows
print(f)

[[0.51118716 0.26063201 0.46418358]
 [0.78095833 0.70157772 0.73821406]
 [0.42098844 0.67298701 0.17102865]
 [0.03835911 0.78796631 0.2101025 ]
 [0.58704319 0.90943591 0.52954651]
 [0.387443   0.11507258 0.11190184]]
[[0.51118716 0.78095833 0.42098844 0.03835911 0.58704319 0.387443  ]
 [0.26063201 0.70157772 0.67298701 0.78796631 0.90943591 0.11507258]
 [0.46418358 0.73821406 0.17102865 0.2101025  0.52954651 0.11190184]]


In [13]:
n = 2
p = 3
g = np.random.random((n,p))
h = np.random.random((p,n))
dotprod = np.dot(g, h)
print(g)
print(h)
print(dotprod)

[[0.89376824 0.12147482 0.51914029]
 [0.15850324 0.46501542 0.42975458]]
[[0.32774177 0.59927082]
 [0.38771175 0.97242968]
 [0.49031566 0.4262316 ]]
[[0.59456501 0.87500894]
 [0.44295547 0.73035614]]
